[2025-08-17 10:50:44,945: INFO]: main: logging is implemented]
[2025-09-01 21:19:19,237: INFO]: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-09-01 21:19:19,243: INFO]: common: yaml file: config\config.yaml loaded successfully]
[2025-09-01 21:19:19,243: INFO]: common: yaml file: params.yaml loaded successfully]
[2025-09-01 21:19:19,247: ERROR]: main: yaml file is empty]
Traceback (most recent call last):
  File "D:\Projects\TextSummarizer\src\textSummarizer\utils\common.py", line 31, in read_yaml
    return ConfigBox(content)
  File "box\box.py", line 259, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\TextSummarizer\main.py", line 9, in <module>
    data_ingestion.main()
  File "D:\Projects\TextSummarizer\src\textSummarizer\pipeline\stage_1_data_ingestion_pipeline.py", line 11, in main
    config = ConfigurationManager()
  File "D:\Projects\TextSummarizer\src\textSummarizer\config\configuration.py", line 13, in __init__
    self.params = read_yaml(params_filepath)
  File "D:\Projects\TextSummarizer\venv\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "D:\Projects\TextSummarizer\src\textSummarizer\utils\common.py", line 33, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2025-09-01 21:21:03,969: INFO]: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-09-01 21:21:03,986: INFO]: common: yaml file: config\config.yaml loaded successfully]
[2025-09-01 21:21:03,987: INFO]: common: yaml file: params.yaml loaded successfully]
[2025-09-01 21:21:03,987: ERROR]: main: yaml file is empty]
Traceback (most recent call last):
  File "D:\Projects\TextSummarizer\src\textSummarizer\utils\common.py", line 31, in read_yaml
    return ConfigBox(content)
  File "box\box.py", line 259, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\TextSummarizer\main.py", line 9, in <module>
    data_ingestion.main()
  File "D:\Projects\TextSummarizer\src\textSummarizer\pipeline\stage_1_data_ingestion_pipeline.py", line 11, in main
    config = ConfigurationManager()
  File "D:\Projects\TextSummarizer\src\textSummarizer\config\configuration.py", line 13, in __init__
    self.params = read_yaml(params_filepath)
  File "D:\Projects\TextSummarizer\venv\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "D:\Projects\TextSummarizer\src\textSummarizer\utils\common.py", line 33, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2025-09-01 21:21:30,315: INFO]: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-09-01 21:21:30,315: INFO]: common: yaml file: config\config.yaml loaded successfully]
[2025-09-01 21:21:30,335: INFO]: common: yaml file: params.yaml loaded successfully]
[2025-09-01 21:21:30,335: INFO]: common: created directory at: artifacts]
[2025-09-01 21:21:30,335: ERROR]: main: name 'data_ingestion_config' is not defined]
Traceback (most recent call last):
  File "D:\Projects\TextSummarizer\main.py", line 9, in <module>
    data_ingestion.main()
  File "D:\Projects\TextSummarizer\src\textSummarizer\pipeline\stage_1_data_ingestion_pipeline.py", line 12, in main
    logger.info(f"Data Ingestion config: {data_ingestion_config}")
NameError: name 'data_ingestion_config' is not defined
[2025-09-01 21:25:33,805: INFO]: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-09-01 21:25:33,805: ERROR]: main: DataIngestionTrainingPipeline.__init__() got an unexpected keyword argument 'config']
Traceback (most recent call last):
  File "D:\Projects\TextSummarizer\main.py", line 8, in <module>
    data_ingestion = DataIngestionTrainingPipeline(config=None)
TypeError: DataIngestionTrainingPipeline.__init__() got an unexpected keyword argument 'config'
[2025-09-01 21:26:51,989: INFO]: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-09-01 21:26:51,989: INFO]: common: yaml file: config\config.yaml loaded successfully]
[2025-09-01 21:26:51,994: INFO]: common: yaml file: params.yaml loaded successfully]
[2025-09-01 21:26:51,994: INFO]: common: created directory at: artifacts]
[2025-09-01 21:26:51,994: INFO]: common: created directory at: artifacts/data_ingestion]
[2025-09-01 21:26:54,209: INFO]: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 55D0:2EBB3A:321459:8A85E1:68B6018D
Accept-Ranges: bytes
Date: Mon, 01 Sep 2025 20:26:55 GMT
Via: 1.1 varnish
X-Served-By: cache-lhr-egll1980087-LHR
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1756758415.684987,VS0,VE333
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 355f7ad5ef7d291868fa8c292b6561bb707e7b86
Expires: Mon, 01 Sep 2025 20:31:55 GMT
Source-Age: 0

]
[2025-09-01 21:26:54,337: INFO]: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-09-04 21:52:09,622: INFO]: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-09-04 21:52:09,622: INFO]: common: yaml file: config\config.yaml loaded successfully]
[2025-09-04 21:52:09,654: INFO]: common: yaml file: params.yaml loaded successfully]
[2025-09-04 21:52:09,654: INFO]: common: created directory at: artifacts]
[2025-09-04 21:52:09,655: INFO]: common: created directory at: artifacts/data_ingestion]
[2025-09-04 21:52:09,655: INFO]: data_ingestion: File already exists of size: ~ 7718 KB]
[2025-09-04 21:52:09,760: INFO]: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-09-04 21:53:51,609: INFO]: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-09-04 21:53:51,609: INFO]: common: yaml file: config\config.yaml loaded successfully]
[2025-09-04 21:53:51,609: INFO]: common: yaml file: params.yaml loaded successfully]
[2025-09-04 21:53:51,609: INFO]: common: created directory at: artifacts]
[2025-09-04 21:53:51,609: INFO]: common: created directory at: artifacts/data_ingestion]
[2025-09-04 21:53:51,609: INFO]: data_ingestion: File already exists of size: ~ 7718 KB]
[2025-09-04 21:53:51,697: INFO]: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-09-04 21:53:51,697: INFO]: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-09-04 21:53:51,697: INFO]: common: yaml file: config\config.yaml loaded successfully]
[2025-09-04 21:53:51,697: INFO]: common: yaml file: params.yaml loaded successfully]
[2025-09-04 21:53:51,697: INFO]: common: created directory at: artifacts]
[2025-09-04 21:53:51,697: INFO]: common: created directory at: artifacts/data_transformation]
[2025-09-04 21:53:56,259: INFO]: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
